stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

  BROWSER:
    value: "edge"
    options:
      - "chrome"
      - "firefox"
      - "edge"
    description: "Select browser to run tests"

  ENVIRONMENT:
    value: "remote"
    options:
      - "local"
      - "remote"
    description: "Select environment"

  SUITE_XML:
    value: "testng-chrome.xml"
    options:
      - "testng-chrome.xml"
      - "testng-firefox.xml"
      - "testng-edge.xml"
      - "testng.xml"
    description: "Select TestNG XML suite"

test:
  image: docker:latest
  services:
    - docker:dind
  stage: test
  before_script:
    - apk add --no-cache bash curl docker-compose
    - curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
    - chmod +x wait-for-it.sh
  script:
    - export BROWSER=$BROWSER
    - export ENVIRONMENT=$ENVIRONMENT
    - export SUITE_XML=$SUITE_XML
    - ./wait-for-it.sh selenium-hub:4444 -t 60
    - docker-compose up --abort-on-container-exit --build
  artifacts:
    when: always
    paths:
      - target/surefire-reports/