name: Run Automation Tests in Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      BROWSER:
        description: 'Select browser to run tests'
        required: false
        default: 'edge'
      ENVIRONMENT:
        description: 'Select environment'
        required: false
        default: 'remote'
      SUITE_XML:
        description: 'Select TestNG XML suite'
        required: false
        default: 'testng-chrome.xml'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BROWSER: ${{ github.event.inputs.BROWSER || 'edge' }}
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT || 'remote' }}
      SUITE_XML: ${{ github.event.inputs.SUITE_XML || 'testng-chrome.xml' }}

    services:
      docker:
        image: docker:20.10.24-dind
        options: >-
          --privileged
          --name docker_service
          -v /var/lib/docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Export Environment Variables
        run: |
          echo "BROWSER=${BROWSER}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${ENVIRONMENT}" >> $GITHUB_ENV
          echo "SUITE_XML=${SUITE_XML}" >> $GITHUB_ENV

      - name: Run Docker Compose
        run: docker-compose up --abort-on-container-exit --build

      - name: Upload TestNG Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/
